query Field($id: ID!) {
  field(id: $id) {
    id
    area
    createdAt
    id
    name
    published_at
    image {
      url
    }
    status
    type
    updatedAt
    seedbeds {
      name
      description
      image {
        url
      }
      width
      height
      type
      number
    }
  }
}
