query Seedbed($id: ID!) {
  seedbed(id: $id) {
    id
    name
    description
    image {
      url
    }
    width
    height
    type
    number
    plants {
      id
      name
      type
      available
      new
      amount
      price
      image {
        url
      }
    }
  }
}
