query Plant($id: ID!) {
  plant(id: $id) {
    id
    name
    type
    available
    new
    amount
    price
    image {
      url
    }
    seedbeds {
      name
      description
      image {
        url
      }
      width
      height
      type
      number
    }
    hotbeds {
      name
      number
      width
      heigth
    }
    cancellations {
      date
      cause
      image {
        url
      }
    }
    winters {
      date
      description
    }
  }
}
